### PR TITLE
Fixed Offset Titlebar In Friendslist

### PR DESCRIPTION
**Pull request by cutekita**
Two values were swapped that applied -10px of left margin on one titlebar but not the other

### CODE REVIEW

**Comment by cutekita** [comment]
actually might have been 20px doesnt matter lol
also, DO NOT USE COPY SELECTOR YOU LOOK LIKE AN ABSOLUTE AMATEUR
ONLY USE IT FOR TESTING, THEN PROVIDE PROPER SELECTORS

**Comment by cutekita** [comment]
found a silly bug, dont merge yet

**Comment by cutekita** [comment]
wait it added my other commit, should have made a branch for it, wonky, welp, you're gonna have to filter it out yourself

**Comment by SlippingGitty** [comment]
i have no idea what i missed while i was asleep but thank you for your help i think 🙃

yes copying the selector in one of the lines was a dumbass move, i forgot to leave that out LMAO

uhhh i'll look over this pull in a minute or provide my own solution later

edit: adapted & renovated concepts from here, with proper credit

**Review by SlippingGitty — APPROVED** [review]

**Pull request closed without merging**
